/**
 * Generates src/qrCodes.ts — SVG path data for the Pump Book QR codes.
 *
 * The QR matrices are computed here at build time and shipped as plain path
 * strings, so the app renders razor-sharp vector QR codes at any size (phone,
 * projector, print) with NO runtime QR dependency. `qrcode` is a devDependency
 * only and never reaches the browser bundle.
 *
 * Usage:  npm run qr        (or: node scripts/generate-qr.mjs)
 * Rerun this whenever APP_VERSION changes so the download links stay correct.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import QRCode from 'qrcode'

const VERSION = '4.2.1'
const REPO = 'https://github.com/anshyd1/Pump-book'
const PWA = 'https://anshyd1.github.io/Pump-book/'

const TARGETS = {
  pwa: PWA,
  arm64: `${REPO}/releases/download/v${VERSION}/Pump-Book-${VERSION}-arm64.apk`,
  armv7: `${REPO}/releases/download/v${VERSION}/Pump-Book-${VERSION}-armv7.apk`,
  repo: REPO
}

/** Merge horizontal runs of dark modules into a compact SVG path. */
function toPath(data, size) {
  const parts = []
  for (let y = 0; y < size; y += 1) {
    let x = 0
    while (x < size) {
      if (!data[y * size + x]) { x += 1; continue }
      const start = x
      while (x < size && data[y * size + x]) x += 1
      const run = x - start
      parts.push(`M${start} ${y}h${run}v1h-${run}z`)
    }
  }
  return parts.join('')
}

function encode(text) {
  // Level H tolerates ~30% damage — survives glare, folds and low-quality prints.
  const qr = QRCode.create(text, { errorCorrectionLevel: 'H' })
  const size = qr.modules.size
  return { size, path: toPath(qr.modules.data, size) }
}

const here = dirname(fileURLToPath(import.meta.url))
const target = resolve(here, '../src/qrCodes.ts')

const entries = Object.entries(TARGETS).map(([key, url]) => {
  const { size, path } = encode(url)
  return { key, url, size, path }
})

const body = entries
  .map(({ key, url, size, path }) => `  ${key}: { url: '${url}', size: ${size}, path: '${path}' }`)
  .join(',\n')

writeFileSync(target, `// AUTO-GENERATED by scripts/generate-qr.mjs — do not edit by hand.
// Regenerate after a version bump:  npm run qr
//
// QR error correction level H (~30% recoverable) stored as SVG path data, so the
// codes stay crisp at any resolution and cost the bundle nothing at runtime.

export type QrTarget = 'pwa' | 'arm64' | 'armv7' | 'repo'

export type QrCode = {
  /** Destination encoded in the code. */
  url: string
  /** Module count per side; use as the SVG viewBox extent. */
  size: number
  /** SVG path data covering every dark module. */
  path: string
}

export const QR_CODES: Record<QrTarget, QrCode> = {
${body}
}

export const APP_VERSION = '${VERSION}'
export const REPO_URL = '${REPO}'
export const PWA_URL = '${PWA}'
export const RELEASE_URL = '${REPO}/releases/tag/v${VERSION}'
export const ARM64_URL = QR_CODES.arm64.url
export const ARMV7_URL = QR_CODES.armv7.url
`)

console.log(`Wrote ${target}`)
for (const { key, size, url } of entries) {
  console.log(`  ${key.padEnd(6)} ${size}x${size}  ${url}`)
}
