type ReadingRow = { nozzle: string; fuel: string; opening: string; closing: string; sale: string }
type FuelRow = { fuel: string; gross: string; testing: string; net: string; rate: string; amount: string }
type PaymentRow = { label: string; value: string }
type Props = {
  date: string; note: string; mode: string; readings: ReadingRow[]; fuels: FuelRow[]; payments: PaymentRow[]
  finalSale: string; accounted: string; balance: string; matched: boolean
}

export default function PrintReport(props: Props) {
  return <section className="print-sheet">
    <header className="print-sheet-head">
      <div><span className="print-monogram">PB</span><div><h1>PUMP BOOK</h1><p>DAILY FUEL &amp; CASH RECONCILIATION</p></div></div>
      <table><tbody><tr><th>Date</th><td>{props.date}</td></tr><tr><th>Machine / Staff</th><td>{props.note || '—'}</td></tr><tr><th>Mode</th><td>{props.mode}</td></tr></tbody></table>
    </header>

    <div className="print-section-title">A. TOTALIZER READINGS</div>
    <table className="print-data-table">
      <thead><tr><th>Nozzle</th><th>Product</th><th>Opening / Morning</th><th>Closing / Evening</th><th>Sale Qty (L)</th></tr></thead>
      <tbody>{props.readings.map(row => <tr key={row.nozzle}><td>{row.nozzle}</td><td>{row.fuel}</td><td>{row.opening}</td><td>{row.closing}</td><td className="num strong">{row.sale}</td></tr>)}</tbody>
    </table>

    <div className="print-two-col">
      <div><div className="print-section-title">B. FUEL SALE</div><table className="print-data-table compact"><thead><tr><th>Fuel</th><th>Gross L</th><th>Test L</th><th>Net L</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{props.fuels.map(row => <tr key={row.fuel}><td>{row.fuel}</td><td>{row.gross}</td><td>{row.testing}</td><td>{row.net}</td><td>{row.rate}</td><td className="strong">{row.amount}</td></tr>)}</tbody></table></div>
      <div><div className="print-section-title">C. PAYMENT BREAKUP</div><table className="print-data-table compact payment-print"><tbody>{props.payments.map(row => <tr key={row.label}><th>{row.label}</th><td>{row.value}</td></tr>)}</tbody></table></div>
    </div>

    <div className="print-recon">
      <div><span>FINAL FUEL SALE</span><b>{props.finalSale}</b></div>
      <div><span>TOTAL ACCOUNTED</span><b>{props.accounted}</b></div>
      <div><span>BALANCE / FAULT</span><b>{props.balance}</b></div>
      <div className={props.matched ? 'print-match' : 'print-check'}><span>STATUS</span><b>{props.matched ? 'MATCH ✓' : 'CHECK !'}</b></div>
    </div>
    <footer className="print-signatures"><div>Prepared by / Operator</div><div>Checked by / Manager</div><div>Dealer signature</div></footer>
    <p className="print-footnote">Generated by Pump Book · All figures should be verified against source slips before final submission.</p>
  </section>
}
